### ISSUE TITLE
tr:has(> .someClass) causes failure

### ISSUE THREAD

**Issue by lglowania** [phax/ph-css#112]
During recent development we added this to our css:

```css

.tableView tr:has(> .error) {
    position: relative;
}
```

Since that change this line returns `null`:

```java

 CascadingStyleSheet css = CSSReader.readFromFile(file, StandardCharsets.UTF_8, ECSSVersion.CSS30);
```
