### ISSUE TITLE
Parsers skips more content than browsers in case of error in browser-compliant mode

### ISSUE THREAD

**Issue by givankin** [phax/ph-css#24]
Hi Philip. So, another issue from the fields. Here's the excerpt from one CSS file, and the error-handling is slightly different as outlined in comments:

```css
/* correct part */
table.fast th, table.fast td {
    padding: 10px 10px;
    text-align: left;
}
/* error that should be skipped*/
table.fast th background:#eee;

/* first correct part that skipped by both browsers and parser algorithm */
.ir {
    display: block;
}

/* correct part that is skipped by parser but is read by browsers */
div.flexible-detail-left {
    margin-bottom: 30px;
}
/* end of skipped part */

.some { more: css; }
```

**Comment by phax** [comment]
I've created a test for it on the HEAD version and the results are imho valid:
```css
table.fast th,
table.fast td {
  padding:10px 10px;
  text-align:left;
}

div.flexible-detail-left { margin-bottom:30px; }

.some { more:css; }
```

**Comment by phax** [comment]
The same output for the 4.1.2 version.

**Comment by korvindest** [comment]
Hello Philip, I am starter of this request. My apologies for incorrect test case.
This is the original CSS with trouble for us.
http://pastebin.com/L1aXFSiq
I tried to minimalize the test case, but looks like I failed to do it.
As you can see in this example ".hidden" style applies correctly with original CSS.
https://jsfiddle.net/ka19ejud/
But it will be cropped after CSS parsing in our case.

**Comment by phax** [comment]
Hi! The problem is the missing `{` which leads to unbalanced brackets and the input is skipped to the end.
I'm using this input:
```css
body {
    margin: 0;
}

table.fast th background:#eee;
/* error that should be skipped*/
padding-left:0;
font-size:14px;
font-weight:bold;
line-height:22px;
color:#c11a12;
white-space:nowrap;
}
/* end of skipped part */

.some { more: css; }
```
and the wrong result is:
``´
body { margin:0; }
```
