### ISSUE TITLE
CSSReader returns null when there is an error in the CSS string

### ISSUE THREAD

**Issue by eduardcotmrf** [phax/ph-css#41]
We are having this code that loads the CSS from a string:

``` JAVA
CSSReaderSettings settings = new CSSReaderSettings();
settings.setCSSVersion(ECSSVersion.CSS30);
settings.setBrowserCompliantMode(false);

return CSSReader.readFromStringReader(initialStyles, settings); 
```

If there is an error, for instance, if there is something malformed in the CSS (throws an Unrecoverable Error ), or incorrect in a line it returns null. There is any way to have it return everything but deleting the failing line?

For example:
``` CSS
@media (min--moz-device-pixel-ratio: 1.3),(-o-min-device-pixel-ratio: 2.6/2),(-webkit-min-device-pixel-ratio: 1.3),(min-device-pixel-ratio: 1.3),(min-resolution: 1.3dppx) {
 .social .facebook a, .social .twitter a {
  background-size: -webkit-background-size: 652px 295px;
  background-size: 652px 295px;
 }
}
```
Desired output, basicilly to ignore the failing line:
``` CSS
@media (min--moz-device-pixel-ratio: 1.3),(-o-min-device-pixel-ratio: 2.6/2),(-webkit-min-device-pixel-ratio: 1.3),(min-device-pixel-ratio: 1.3),(min-resolution: 1.3dppx) {
 .social .facebook a, .social .twitter a {
  background-size: 652px 295px;
 }
}
```

**Comment by phax** [comment]
Try switching "browser compliant mode" to `true`. This should help you...

**Comment by juanchaur1** [comment]
@phax I believe there's a problem with the fallbacks when setting that setting to true.
In ParseCSS30.jjt as the default is a Throw Exception handler, it will actually never go to the next bracket but instead will throw an ParseException causing the CSSReader.java to return null. 
What we've done as a temporary solution is to set a DoNothingCSSParseErrorHandler in the CSSReaderSettings

**Comment by ronnyshapiro** [comment]
This is not really a bug because the docs say unrecoverable errors return null, but some some additional automatic fixing abilities could be extremely helpful. For example :

`.someRule {
   color:red;
}

------- This is bad`

Returns null;

At the moment we've add a custom exception handler that rethrows the ParseException and removes char by char, using the Token info, until ParseExceptions are no longer thrown, but I'm really unsure about that solution.

Is there any other recommended way to "fix" broken css ? 
What other scenarios may cause such a violent ParseException ? From what i've tested, illegal CSS properties are discarded by toggling, as you suggested, "browser compliant mode" to true.

If the current solution is valid, maybe it can be added as a core feature (PR ?).

**Comment by phax** [comment]
Well, there is a `ICSSParseErrorHandler` that can be overwritten, a `ICSSParseExceptionCallback` and a `ICSSInterpretErrorHandler`. All can be set in class `CSSReaderSettings` and depending on your issue, different solutions might be needed.
Therefore there is no "recommendation" because there is no "one size fits all" solution. Tell me your problem, and I can try suggesting something :)

**Comment by ronnyshapiro** [comment]
The CSS I'm parsing is a user input, so I don't control over what I'm parsing.
The main issue is we're replacing an older Antlr based parser that didn't support nearly as much as this parser does, but it was fault tolerant, so we may have persisted all kind of "bad" css.

We're already setting `DoNothingCSSParseErrorHandler` via `setCustomErrorHandler` and it does recover in many cases, but we still get null in others, like in the example above.

The ideal solution for me is an even more tolerant parse mode which just discards anything it can't handle.

**Comment by phax** [comment]
Okay, will check based on the above example and give you some suggestions

**Comment by phax** [comment]
The best I can come up with is the following output:
```css
@media (min--moz-device-pixel-ratio:1.3), (-o-min-device-pixel-ratio:2.6/2), (-webkit-min-device-pixel-ratio:1.3), (min-device-pixel-ratio:1.3), (min-resolution:1.3dppx) {
 .social .facebook a,
 .social .twitter a { background-size:-webkit-background-size; }
}
```
because `-webkit-background-size` is considered an identifier which would be valid according to the grammar. The only thing I changed is that in this case it is skipped until ";" or "}" - whatever comes first. Previously it was always skipped until "}".
@ronnyshapiro if this helps you, I could create a 6.1.4 release

**Comment by ronnyshapiro** [comment]
I actually posted a different example which breaks the parser : 

```
.someRule {
   color:red;
}

------- This is bad
```

In general any fix that narrows down the inputs resulting in null return values is welcome.

**Comment by phax** [comment]
Okay, I changed browser compliant handling a bit so, that `null` is basically never returned (except in very special cases). The major change was https://github.com/phax/ph-css/commit/4e934857429e915e544210d6b8d0497165eb6b34#diff-f1eefe50aada05202a72ce2502b82b62
Please test the 6.2.0-SNAPSHOT
Additionally I changed the default "Custom error handler" from `Throwing...` to `Logging...` which is an incompatible change, so that's why the version number changed.

**Comment by ronnyshapiro** [comment]
@phax I've experimented with 6.2.0-SNAPSHOT and it works well. I did not get any nulls. Still haven't tested on production with live data yet.
One thing I did see is that now when there's an exception the parser stops and returns the parse result to this point.

For example, if I parse the following css :

```
------- This is bad

.someRule {
   color:red;
}
```

The parser returns a stylesheet with 0 rules. Is there any way this can this be fixed ?
Ideally both example will return the same results.

**Comment by phax** [comment]
Thanks for investing the time to test this :D
Glad that it works for you.

The second case you are mentioning is a lot trickier because it would require a lot of potentially bogus heuristics and I am not sure that this is good....

Try adding another rule after '.someRule'  - it might work than, because a skip to the next closing "}" on the same level might work. (I am not on machine so I cannot test it myself)

**Comment by ronnyshapiro** [comment]
Unfortunately it did not work.

```
------- This is bad

.someRule {
   color:red;
}

.someOtherRule {
   color:blue;
}
```

Returns a sheet with 0 rules.

I understand a generic solution to just "ignore" illegal chars is very problematic. 
If the behaviour you just described (skip to the next closing "}") could work that would still be a major and a very welcomed improvement.

**Comment by phax** [comment]
Okay, so the block
```css
------- This is bad

.someRule {
   color:red;
}

.someOtherRule {
   color:blue;
}
```
will now result in
```css
.someOtherRule {
   color:blue;
}
```

So I consider this to be a big step in fault tolerance :)
