### ISSUE TITLE
var-statements inside calc(..) fail

### ISSUE THREAD

**Issue by lglowania** [phax/ph-css#57]
Failing line is:
```
left: calc(50% - (600px / 2 + var(--page-column-padding-x)));
```

**Comment by phax** [comment]
@lglowania I could successfully parse it with version 6.2.0.
What version are you using?

**Comment by lglowania** [comment]
I was using 6.1 which aborted parsing. I upgraded to 6.2 which tolerates such a statement, but it seems to just skip until closing brace: 
```
05:46:38.031 [main] WARN  c.h.c.r.e.LoggingCSSParseErrorHandler:131 - [1076:31]-[1085:1] Encountered text '* var(' corresponding to token <FUNCTION>. Skipped until token }. Was expecting one of: <S>, ")", <S>
```

**Comment by lglowania** [comment]
This is the full css-block: 
```css
.pageColumn > .center:before{
	content: '';
	position: absolute;
	left: calc(50% - (600px / 2 + var(--page-column-padding-x)));
	width: calc(600px + 2 * var(--page-column-padding-x));
	/* if inside a small contaier e.g. a card, do not exceed width */
	max-width: 100%;
	background: white;
	top: 0;
	min-height: 100%;
	flex: 1;
	bottom: 0px;
	z-index: 0;
}
```
