### ISSUE TITLE
URI Traversing misses uris within functions

### ISSUE THREAD

**Issue by rockwotj** [phax/ph-css#59]
Example CSS:

```css
dd {
    background-image: cross-fade(20% url(http://example.com/first.png), url(/second.png));
}
```

I would expect that this example: https://github.com/phax/ph-css/blob/master/ph-css/src/test/java/com/helger/css/supplementary/wiki/WikiVisitDataUrls.java

Would print out urls for this snippet, but it does not.
