### ISSUE TITLE
Parser bug

### ISSUE THREAD

**Issue by Panthevm** [phax/ph-css#63]
When forming a `CSSDeclaration`, the `.getProperty` is always formed in lowercase.

This error is critical when we are dealing with variables.

`--A != --a`

And when call `.getExpressionAsCSSString`, the case is respected, as a result, we lose the relationship

Reproducing an error: https://jsfiddle.net/dauhk27r/

**Comment by phax** [comment]
Quote from https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
> Note: Custom property names are case sensitive — --my-color will be treated as a separate custom property to --My-color.

**Comment by phax** [comment]
I created a test case with your example, where I am reading and re-emitting the file. The output is
```css
body {
  --a:red;
  background-color:var(--A);
}
```

so that looks good to me.
When calling `expression.getAsCSSString()` I also get it in the right casing.

**Comment by Panthevm** [comment]
> Quote from https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
> 
> > Note: Custom property names are case sensitive — --my-color will be treated as a separate custom property to --My-color.


I apparently did not explain the problem well. You quoted above that variable names are ‘case sensitive’, but your reader will always format them in ‘lower case’. And as a result, you get what you brought in the tests - not valid css, since there is no ‘--A’ variable. since its parser brought it to lower case

**Comment by Panthevm** [comment]
Input:

``` css

body {
  --A:red;
  background-color:var(--A);
}

```

Output:

``` css

body {
  --a:red;
  background-color:var(--A);
}

```

`—A` - not found
