### ISSUE TITLE
Support `@supports`

### ISSUE THREAD

**Issue by nafg** [phax/ph-css#90]
Parsing https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.1/dist/semantic.css fails with

`ERROR com.helger.css.handler.LoggingCSSParseExceptionCallback - Failed to parse CSS: [36251:11] Encountered text 'selector(' corresponding to token <FUNCTION>. Was expecting one of: <S>, "(", "not"`

At line 36251 is

```css
@supports selector(:has(.f)) {
  .ui.icon.input:not([class*="left icon"]) > .ui.dropdown > .dropdown.icon {
    padding-right: initial;
  }

  .ui.icon.input:not([class*="left icon"]):not(:has(.ui.dropdown ~ input)) > .ui.dropdown > .dropdown.icon {
    padding-right: 2.5em;
  }
}
```
